// ============================================
// FILTER-COMPATIBLE COMPANY DATA MODEL
// ============================================

export type Major = 'CS' | 'ECE' | 'EEE' | 'Core' | 'Math' | 'Finance';
export type Tier = 'Tier 1' | 'Tier 2' | 'Tier 3';
export type LocationType = 'Remote' | 'On-site' | 'Hybrid';
export type CompanyType = 'Product' | 'Startup' | 'PSU' | 'Service';
export type Difficulty = 'Easy' | 'Medium' | 'Hard';
export type WLB = 'Green' | 'Yellow' | 'Red';
export type Learning = 'High' | 'Medium' | 'Low';
export type Level =
    | 'Internship' | 'Entry Level' | 'Mid Level' | 'Senior'
    | 'Staff' | 'Architect' | 'Expert'
    | 'GET' | 'Engineer' | 'Assistant Manager' | 'Senior Manager'
    | 'GT' | 'E1' | 'E2' | 'E3' | 'E4'
    | 'Scientist/Engineer-SC' | 'SD' | 'SE' | 'SF' | 'SG'
    | 'Design Trainee' | 'Probationary Officer' | 'Senior Engineer' | 'Construction Manager';


export interface Company {
    id: string;
    name: string;
    tier: Tier;
    majors: Major[];
    domains: string[];
    roleTypes: string[];
    location: LocationType;
    companyType: CompanyType;
    difficulty: Difficulty;
    internFriendly: boolean;
    levels?: Level[]; // Experience levels offered
    salary: {
        minLPA: number;
        maxLPA: number;
        inHandPercent: number;
    };
    culture: {
        wlb: WLB;
        learning: Learning;
    };
    description?: string;
    whyJoin?: string[];
    tags?: string[];
    detailedAnalysis?: {
        pros: string[];
        cons: string[];
        recentDevelopments: string[];
        highlight?: string;
    };
    internship?: {
        role: string;
        minStipend: number;
        maxStipend: number;
        duration?: string;
    };
}

export const TIER_TOOLTIPS: Record<Tier, string> = {
    'Tier 1': 'Elite / Highly competitive companies',
    'Tier 2': 'Strong product companies with good growth',
    'Tier 3': 'Intern-friendly / Growing firms'
};

// ============================================
// CS COMPANIES
// ============================================

const CS_TIER1: Company[] = [
    {
        id: 'google-india',
        name: 'Google India',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['AI/ML', 'Cloud', 'Systems', 'Backend'],
        roleTypes: ['SWE', 'Research', 'SRE'],
        internship: {
            role: "Software Engineering Intern",
            minStipend: 100000,
            maxStipend: 125000,
            duration: "10-12 Weeks"
        },
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior'],
        salary: { minLPA: 32, maxLPA: 60, inHandPercent: 70 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Search, cloud and ads. Top-tier pay and benefits.',
        whyJoin: ['Building Gemini & AI First Future', 'World-class engineering', 'Market-leading compensation (s. Levels.fyi)', 'High pay'],
        detailedAnalysis: {
            pros: [
                "**Engineering Heaven**: Access to internal tools (Borg, Blaze) and Gemini 1.5 Pro models.",
                "**Top Market Pay**: Levels.fyi data indicates L3 (Entry) starts ~₹35LPA TC.",
                "**Perks**: Free food, fertility assistance, and top-tier health insurance.",
                "**Internal Mobility**: Easy to switch teams after 18 months."
            ],
            cons: [
                "**Promotion Velocity**: Promotions have become significantly slower (Project 'Googler Reviews' impact). L4 to L5 is a bottleneck.",
                "**Bureaucracy**: Launching anything requires multiple approvals. Feature velocity can feel slow compared to startups.",
                "**Top-Down Culture**: Recent leadership changes have made it feel more corporate and less 'bottom-up' innovation driven."
            ],
            recentDevelopments: [
                "**Gemini Era**: Massive internal Pivot to AI. Almost every team is integrating LLMs. Great time to join if you want GenAI experience.",
                "**Layoffs & Efficiency**: 2024 saw silent layoffs and role eliminations. 'Resting and vesting' is dead.",
                "**AI Dominance**: Working on Copilot stack and Azure OpenAI Service is a resume goldmine.",
                "**Office Policy**: Strict 3 days/week in office mandate is being enforced via badge tracking."
            ],
            highlight: "Google is no longer the 'retirement home' for engineers. It's in wartime mode to fight OpenAI/Microsoft. Expect harder work but cutting-edge AI exposure."
        }
    },
    {
        id: 'amazon',
        name: 'Amazon / AWS',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Cloud', 'Backend', 'Distributed Systems'],
        roleTypes: ['SDE', 'Backend', 'DevOps'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 26, maxLPA: 55, inHandPercent: 72 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Cloud, backend & systems. High scale engineering.',
        whyJoin: ['Bar Raiser Culture', 'Fast Promotion Velocity', 'Working on AWS Bedrock / Q'],
    },
    {
        id: 'microsoft',
        name: 'Microsoft',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Cloud', 'AI/ML', 'Enterprise'],
        roleTypes: ['SWE', 'AI/ML', 'Full-Stack'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 22, maxLPA: 50, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Enterprise software, cloud and AI.',
        whyJoin: ['Leading the AI Revolution (OpenAI)', 'Great WLB for Tier 1', 'ESOPs are liquid like cash'],
    },
    {
        id: 'apple',
        name: 'Apple',
        tier: 'Tier 1',
        majors: ['CS', 'ECE'],
        domains: ['Systems', 'Silicon', 'Embedded'],
        roleTypes: ['SWE', 'Systems', 'Embedded'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: false,
        salary: { minLPA: 16, maxLPA: 40, inHandPercent: 73 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Consumer OS, silicon and systems teams.',
        whyJoin: ['Premium brand', 'Hardware-software integration', 'Top pay', 'Secretive but rewarding'],
    },
    {
        id: 'meta',
        name: 'Meta',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['AI/ML', 'Backend', 'Infrastructure'],
        roleTypes: ['SWE', 'AI/ML', 'Infra'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 20, maxLPA: 45, inHandPercent: 76 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Social, ads and large-scale ML systems.',
        whyJoin: ['Highest base salaries', 'Fast-paced culture', 'Great for infra roles'],
    },
    {
        id: 'netflix',
        name: 'Netflix',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Backend', 'Data', 'Streaming'],
        roleTypes: ['SWE', 'Backend', 'Data'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: false,
        salary: { minLPA: 25, maxLPA: 50, inHandPercent: 78 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Streaming infra and data-intensive systems.',
        whyJoin: ['Highest paying globally', 'Keeper test culture', 'Ultra selective'],
    },
    {
        id: 'stripe',
        name: 'Stripe',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Payments', 'Backend', 'Fintech'],
        roleTypes: ['SWE', 'Backend', 'Security'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 18, maxLPA: 40, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Payments infra and APIs.',
        whyJoin: ['Payments infrastructure leader', 'Remote-friendly', 'High engineering bar'],
    },
    {
        id: 'jane-street',
        name: 'Jane Street',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Quant', 'Trading', 'Systems'],
        roleTypes: ['Quant-Dev', 'SWE'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 50, maxLPA: 150, inHandPercent: 80 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Quant trading and research — highly selective.',
        whyJoin: ['Highest paying globally', 'OCaml expertise', 'Ultra elite'],
    },
    {
        id: 'citadel',
        name: 'Citadel',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Quant', 'Trading', 'Systems'],
        roleTypes: ['Quant-Eng', 'SWE', 'Data'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 40, maxLPA: 120, inHandPercent: 80 },
        culture: { wlb: 'Red', learning: 'High' },
        description: 'Hedge fund with quant/engineering roles.',
        whyJoin: ['Top quant firm', 'C++ mastery required', 'Brutal interviews'],
    },
    {
        id: 'openai',
        name: 'OpenAI',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['AI/ML', 'Research', 'Infrastructure'],
        roleTypes: ['ML Research', 'SWE', 'Infra'],
        location: 'Hybrid',
        companyType: 'Startup',
        difficulty: 'Hard',
        internFriendly: false,
        salary: { minLPA: 30, maxLPA: 80, inHandPercent: 78 },
        culture: { wlb: 'Red', learning: 'High' },
        description: 'State-of-the-art ML research and products.',
        whyJoin: ['AI frontier', 'ChatGPT creators', 'Most competitive globally'],
    },
    {
        id: 'nvidia-sw',
        name: 'NVIDIA (Software)',
        tier: 'Tier 1',
        majors: ['CS', 'ECE'],
        domains: ['AI/ML', 'GPU', 'Systems'],
        roleTypes: ['ML', 'SWE', 'GPU-Infra'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 20, maxLPA: 45, inHandPercent: 76 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'GPU software, ML libraries and developer tools.',
        whyJoin: ['AI hardware leader', 'CUDA expertise valuable', 'Great for ML engineers'],
    },
    {
        id: 'salesforce',
        name: 'Salesforce',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Cloud', 'Enterprise', 'CRM'],
        roleTypes: ['SWE', 'Backend', 'Product'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 30, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'CRM and enterprise SaaS platform.',
        whyJoin: ['Great WLB', 'Ohana culture', 'Stable and growing'],
    },
    {
        id: 'bloomberg',
        name: 'Bloomberg',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Fintech', 'Data', 'Backend'],
        roleTypes: ['SWE', 'Data', 'Backend'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 30, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Financial data terminals & analytics.',
        whyJoin: ['Finance + tech blend', 'Great WLB', 'Strong engineering culture'],
    },
    {
        id: 'linkedin',
        name: 'LinkedIn',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Social', 'Data', 'AI/ML'],
        roleTypes: ['SWE', 'Data', 'ML'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 25, maxLPA: 80, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Professional networking platform.',
        whyJoin: ['Great WLB', 'Top-tier pay', 'Massive data scale'],
    },
    {
        id: 'x-twitter',
        name: 'X (Twitter)',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Social', 'Systems', 'AI/ML'],
        roleTypes: ['SWE', 'ML', 'Backend'],
        internship: {
            role: "Software Engineering Intern",
            minStipend: 100000,
            maxStipend: 150000,
        },
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 30, maxLPA: 160, inHandPercent: 80 },
        culture: { wlb: 'Red', learning: 'High' },
        description: 'The "Everything App". High intensity engineering.',
        whyJoin: ['Rebuilding everything', 'High equity upside', 'Hardcore engineering'],
    },
    {
        id: 'kognitos',
        name: 'Kognitos',
        tier: 'Tier 1', // Startups can be Tier 1 based on pay/talent
        majors: ['CS'],
        domains: ['AI/ML', 'Automation', 'GenAI'],
        roleTypes: ['SWE', 'ML'],
        internship: {
            role: "AI Engineering Intern",
            minStipend: 80000,
            maxStipend: 120000,
        },
        location: 'On-site',
        companyType: 'Startup',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 40, maxLPA: 120, inHandPercent: 85 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Generative AI for business automation.',
        whyJoin: ['Top paying startup in India', 'Cutting edge GenAI', 'Early stage equity'],
    },
    {
        id: 'airbnb',
        name: 'Airbnb',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Cloud', 'Backend', 'Systems'],
        roleTypes: ['SDE', 'Cloud Support'],
        internship: {
            role: "SDE Intern",
            minStipend: 80000,
            maxStipend: 110000,
            duration: "6 Months / 2 Months"
        },
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 35, maxLPA: 100, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Global travel community marketplace.',
        whyJoin: ['Strong design culture', 'Great benefits', 'Global impact'],
    },
    {
        id: 'goldman-sachs',
        name: 'Goldman Sachs',
        tier: 'Tier 1',
        majors: ['CS', 'Math', 'Finance'],
        domains: ['Fintech', 'Systems', 'Quant'],
        roleTypes: ['Analyst', 'Associate', 'Quant'],
        internship: {
            role: "Systems Intern / Quant Intern",
            minStipend: 150000,
            maxStipend: 200000,
            duration: "10 Weeks"
        },
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium', // Often mass hiring for analysts
        internFriendly: true,
        salary: { minLPA: 22, maxLPA: 45, inHandPercent: 85 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Global investment banking and securities.',
        whyJoin: ['Prestigious brand', 'High bonuses', 'Strong alumni network'],
    },
    {
        id: 'prophecy',
        name: 'Prophecy',
        tier: 'Tier 1',
        majors: ['CS'],
        domains: ['Data', 'Low-Code', 'Cloud'],
        roleTypes: ['SWE', 'Platform'],
        location: 'On-site',
        companyType: 'Startup',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 30, maxLPA: 90, inHandPercent: 80 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Low-code data engineering platform.',
        whyJoin: ['High startup pay', 'Modern tech stack', 'Rapid growth'],
    }
];

const CS_TIER2: Company[] = [
    {
        id: 'oracle',
        name: 'Oracle',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['Cloud', 'Database', 'Enterprise'],
        roleTypes: ['MTS', 'SWE', 'Cloud'],
        internship: {
            role: "Project Intern",
            minStipend: 50000,
            maxStipend: 80000,
        },
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 16, maxLPA: 40, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Cloud infrastructure and database giant.',
        whyJoin: ['Stability', 'OCI is growing', 'Good WLB'],
    },
    {
        id: 'hackerrank',
        name: 'HackerRank',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['OS', 'Cloud', 'AI/ML', 'Gaming'],
        roleTypes: ['SWE', 'Product'],
        internship: {
            role: "Software Engineering Intern",
            minStipend: 125000,
            maxStipend: 150000,
            duration: "8-12 Weeks"
        },
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 18, maxLPA: 45, inHandPercent: 80 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Tech hiring platform for developers.',
        whyJoin: ['Top tech hiring platform', 'Strong engineering culture', 'Remote-friendly'],
    },
    {
        id: 'glance',
        name: 'Glance (InMobi)',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['Mobile', 'AdTech', 'AI/ML'],
        roleTypes: ['SWE', 'Android', 'ML'],
        location: 'On-site',
        companyType: 'Startup', // Unicorn
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 20, maxLPA: 45, inHandPercent: 78 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Lock-screen content platform.',
        whyJoin: ['Unicorn startup', 'InMobi pedigree', 'Consumer-scale tech'],
    },
    {
        id: 'trellix',
        name: 'Trellix',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['Security', 'Cybersecurity', 'Cloud'],
        roleTypes: ['SWE', 'Security Researcher'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 18, maxLPA: 40, inHandPercent: 80 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Cybersecurity and threat intelligence.',
        whyJoin: ['Cybersecurity leader', 'Good WLB', 'Learn security at scale'],
    },
    {
        id: 'adobe',
        name: 'Adobe',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['SaaS', 'Design Tools', 'Cloud'],
        roleTypes: ['SWE', 'Full-Stack', 'Cloud'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 20, maxLPA: 35, inHandPercent: 73 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Creative & document management software.',
        whyJoin: ['Creative Cloud Leader', 'Great WLB', 'Research Focus'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'atlassian',
        name: 'Atlassian',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['SaaS', 'Collaboration', 'Cloud'],
        roleTypes: ['SWE', 'Product', 'Cloud'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 35, maxLPA: 75, inHandPercent: 73 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Jira, Confluence — team collaboration tools.',
        whyJoin: ['Remote-First Forever', 'Great WLB', 'Top Compensation'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'uber',
        name: 'Uber',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['Mobility', 'Backend', 'ML'],
        roleTypes: ['SWE', 'Backend', 'ML'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 30, maxLPA: 70, inHandPercent: 72 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Mobility, backend systems and market platforms.',
        whyJoin: ['High Scale Engineering', 'Top Tier Pay', 'Fast Paced'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior', 'Staff'],
        internship: {
            role: "Software Engineer Intern",
            minStipend: 160000,
            maxStipend: 160000,
        },
    },
    {
        id: 'mongodb',
        name: 'MongoDB',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['Database', 'Cloud', 'SaaS'],
        roleTypes: ['SWE', 'DB-Eng', 'SRE'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 30, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Document DB and developer platform.',
        whyJoin: ['Database Leader', 'Remote Friendly', 'Strong Engineering'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior', 'Staff']
    },
    {
        id: 'zoho',
        name: 'Zoho',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['SaaS', 'Enterprise', 'CRM'],
        roleTypes: ['SWE', 'Full-Stack', 'Cloud'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 6, maxLPA: 18, inHandPercent: 78 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Indian enterprise SaaS with wide product suite.',
        whyJoin: ['Profitable Bootstrap', 'Rural Offices', 'Great Food'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'postman',
        name: 'Postman',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['DevTools', 'API', 'SaaS'],
        roleTypes: ['SWE', 'Platform', 'Product'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 10, maxLPA: 28, inHandPercent: 73 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'API development and collaboration platform.',
        whyJoin: ['API Platform Leader', 'Remote First', 'Global Impact'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior', 'Staff']
    },
    {
        id: 'browserstack',
        name: 'BrowserStack',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['DevTools', 'Testing', 'SaaS'],
        roleTypes: ['SWE', 'DevTools', 'SRE'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 24, inHandPercent: 76 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Cross-browser testing & dev tools.',
        whyJoin: ['SaaS Unicorn', 'Profitable', 'Scale Engineering'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'freshworks',
        name: 'Freshworks',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['SaaS', 'CRM', 'Enterprise'],
        roleTypes: ['SWE', 'Product', 'Cloud'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 6, maxLPA: 18, inHandPercent: 76 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Customer engagement & CRM SaaS from India.',
        whyJoin: ['SaaS Pioneer', 'Great Culture', 'Public Company'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'shopify',
        name: 'Shopify',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['E-commerce', 'SaaS', 'Cloud'],
        roleTypes: ['SWE', 'Full-Stack', 'Backend'],
        location: 'Remote',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 20, maxLPA: 45, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'E-commerce platform for online stores.',
        whyJoin: ['Remote-First', 'Strong Engineering Culture', 'High Growth'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'dropbox',
        name: 'Dropbox',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['Cloud Storage', 'SaaS', 'Infrastructure'],
        roleTypes: ['SWE', 'Backend', 'Infrastructure'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 18, maxLPA: 40, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Cloud storage and file collaboration platform.',
        whyJoin: ['Distributed Systems', 'Great WLB', 'Strong Engineering'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'snowflake',
        name: 'Snowflake',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['Data Warehouse', 'Cloud', 'Analytics'],
        roleTypes: ['SWE', 'Data Engineer', 'Backend'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 25, maxLPA: 55, inHandPercent: 76 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Cloud data warehouse and analytics platform.',
        whyJoin: ['Data Infrastructure Leader', 'High Compensation', 'Cutting Edge'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'databricks',
        name: 'Databricks',
        tier: 'Tier 2',
        majors: ['CS'],
        domains: ['Data', 'AI/ML', 'Analytics'],
        roleTypes: ['SWE', 'Data Engineer', 'ML Engineer'],
        location: 'Hybrid',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 28, maxLPA: 60, inHandPercent: 77 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Unified analytics platform built on Apache Spark.',
        whyJoin: ['Data + AI Leader', 'High Growth', 'Apache Spark Creators'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
];

const CS_TIER3: Company[] = [
    {
        id: 'paytm',
        name: 'Paytm',
        tier: 'Tier 3',
        majors: ['CS'],
        domains: ['Fintech', 'Payments', 'Backend'],
        roleTypes: ['SWE', 'Backend', 'Payments'],
        location: 'On-site',
        companyType: 'Startup',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 70 },
        culture: { wlb: 'Yellow', learning: 'Medium' },
        description: 'Indian payments and financial services platform.',
        whyJoin: ['High Scale Fintech', 'Fast Paced', 'Impact at Scale'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'phonepe',
        name: 'PhonePe',
        tier: 'Tier 3',
        majors: ['CS', 'ECE', 'EEE'],
        domains: ['Fintech', 'Systems', 'Web'],
        roleTypes: ['Member Technical', 'FTE'],
        internship: {
            role: "System Engineer Intern",
            minStipend: 150000,
            maxStipend: 200000,
            duration: "6 Months"
        },
        location: 'On-site',
        companyType: 'Startup',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 10, maxLPA: 25, inHandPercent: 72 },
        culture: { wlb: 'Yellow', learning: 'Medium' },
        description: 'UPI and payments platform in India.',
        whyJoin: ['UPI Leader', 'Top Compensation', 'ESOP Buybacks'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'razorpay',
        name: 'Razorpay',
        tier: 'Tier 3',
        majors: ['CS'],
        domains: ['Fintech', 'Payments', 'Backend'],
        roleTypes: ['SWE', 'Payments', 'Backend'],
        location: 'On-site',
        companyType: 'Startup',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 28, inHandPercent: 72 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Payments infra for Indian merchants.',
        whyJoin: ['YCombinator Alumni', 'Fintech Innovation', 'Great Engineering'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'groww',
        name: 'Groww',
        tier: 'Tier 3',
        majors: ['CS'],
        domains: ['Fintech', 'Investment', 'Backend'],
        roleTypes: ['SWE', 'Backend', 'Data'],
        location: 'On-site',
        companyType: 'Startup',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 28, inHandPercent: 72 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Investment platform with product & data teams.',
        whyJoin: ['Fast Growing Fintech', 'Modern Tech Stack', 'Ownership'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'zerodha',
        name: 'Zerodha',
        tier: 'Tier 3',
        majors: ['CS'],
        domains: ['Fintech', 'Trading', 'Backend'],
        roleTypes: ['SWE', 'Backend', 'Trading-Infra'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 10, maxLPA: 25, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Retail brokerage & trading platform.',
        whyJoin: ['Bootstrapped Unicorn', 'Tech First', 'No Marketing Clutter'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'cred',
        name: 'CRED',
        tier: 'Tier 3',
        majors: ['CS'],
        domains: ['Fintech', 'Payments', 'Product'],
        roleTypes: ['SWE', 'Backend', 'Product'],
        location: 'On-site',
        companyType: 'Startup',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 15, maxLPA: 35, inHandPercent: 72 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Premium fintech brand focused on credit.',
        whyJoin: ['Design First', 'Top 1% Talent', 'High ESOPs'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'meesho',
        name: 'Meesho',
        tier: 'Tier 3',
        majors: ['CS'],
        domains: ['Ecommerce', 'Backend', 'Growth'],
        roleTypes: ['SWE', 'Backend', 'Growth'],
        location: 'On-site',
        companyType: 'Startup',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 10, maxLPA: 25, inHandPercent: 70 },
        culture: { wlb: 'Red', learning: 'Medium' },
        description: 'Social commerce and marketplace.',
        whyJoin: ['E-commerce Scale', 'Fast Growth', 'High Impact'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'tcs-digital',
        name: 'TCS Digital',
        tier: 'Tier 3',
        majors: ['CS'],
        domains: ['IT Services', 'Consulting'],
        roleTypes: ['SWE', 'Full-Stack'],
        location: 'On-site',
        companyType: 'Service',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 7, maxLPA: 10, inHandPercent: 72 },
        culture: { wlb: 'Yellow', learning: 'Low' },
        description: 'IT services with higher-tier digital practice.',
        whyJoin: ['Digital Projects', 'Upskilling', 'Job Security'],
        levels: ['Entry Level', 'Mid Level', 'Senior']
    },
];

// ============================================
// ECE COMPANIES
// ============================================

const ECE_TIER1: Company[] = [
    {
        id: 'qualcomm',
        name: 'Qualcomm',
        tier: 'Tier 1',
        majors: ['ECE'],
        domains: ['Semiconductor', 'Embedded', 'VLSI', '5G'],
        roleTypes: ['Embedded', 'Firmware', 'VLSI', 'Hardware'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 15, maxLPA: 35, inHandPercent: 78 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Global leader in wireless tech and mobile SoCs.',
        whyJoin: ['Wireless Leader', 'Top Pay in ECE', '5G Innovation'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'texas-instruments',
        name: 'Texas Instruments',
        tier: 'Tier 1',
        majors: ['ECE', 'EEE'],
        domains: ['Analog', 'Embedded', 'Semiconductor'],
        roleTypes: ['Embedded', 'Analog', 'Firmware'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 28, inHandPercent: 76 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Analog chip design for power and industrial.',
        whyJoin: ['Analog Leader', 'Great Culture', 'Long Term Career'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'nvidia-hw',
        name: 'NVIDIA (Hardware)',
        tier: 'Tier 1',
        majors: ['ECE'],
        domains: ['GPU', 'VLSI', 'AI Hardware'],
        roleTypes: ['VLSI', 'Hardware', 'Verification'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 20, maxLPA: 45, inHandPercent: 76 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'GPU computing leader with strong India team.',
        whyJoin: ['AI Hardware King', 'High Stocks', 'Cutting Edge Tech'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior', 'Architect']
    },
    {
        id: 'intel',
        name: 'Intel',
        tier: 'Tier 1',
        majors: ['ECE'],
        domains: ['Semiconductor', 'VLSI', 'CPU'],
        roleTypes: ['VLSI', 'Hardware', 'Verification'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 15, maxLPA: 35, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'x86 chip pioneer with large India R&D.',
        whyJoin: ['CPU Pioneer', 'Great Benefits', 'Large Scale R&D'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'amd',
        name: 'AMD',
        tier: 'Tier 1',
        majors: ['ECE'],
        domains: ['Semiconductor', 'GPU', 'CPU'],
        roleTypes: ['VLSI', 'Hardware', 'Verification'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 15, maxLPA: 35, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'CPU/GPU competitor to Intel/NVIDIA.',
        whyJoin: ['High Growth', 'CPU + GPU', 'Strong Engineering'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'arm',
        name: 'ARM',
        tier: 'Tier 1',
        majors: ['ECE'],
        domains: ['CPU Architecture', 'Embedded', 'Mobile'],
        roleTypes: ['VLSI', 'Hardware', 'CPU Design'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 18, maxLPA: 40, inHandPercent: 76 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'CPU architecture leader for mobile processors.',
        whyJoin: ['Mobile Architecture', 'Global Impact', 'Research Focus'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'broadcom',
        name: 'Broadcom',
        tier: 'Tier 1',
        majors: ['ECE'],
        domains: ['Networking', 'Semiconductor', 'VLSI'],
        roleTypes: ['VLSI', 'Hardware', 'Firmware'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 18, maxLPA: 40, inHandPercent: 75 },
        culture: { wlb: 'Yellow', learning: 'High' },
        description: 'Networking chips and semiconductor solutions.',
        whyJoin: ['Connectivity Leader', 'High Pay', 'Acquisition Growth'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
];

const ECE_TIER2: Company[] = [
    {
        id: 'synopsys',
        name: 'Synopsys',
        tier: 'Tier 2',
        majors: ['ECE'],
        domains: ['EDA', 'VLSI', 'Verification'],
        roleTypes: ['VLSI', 'EDA', 'Verification'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 15, maxLPA: 35, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'EDA tools leader for IC design.',
        whyJoin: ['EDA Market Leader', 'Deep Tech', 'Stable Career'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'cadence',
        name: 'Cadence',
        tier: 'Tier 2',
        majors: ['ECE'],
        domains: ['EDA', 'VLSI', 'Analog'],
        roleTypes: ['VLSI', 'EDA', 'Analog'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 15, maxLPA: 35, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'EDA tools giant for analog/digital.',
        whyJoin: ['Design Automation', 'Innovation', 'Great Benefits'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'micron',
        name: 'Micron',
        tier: 'Tier 2',
        majors: ['ECE'],
        domains: ['Memory', 'Semiconductor', 'DRAM'],
        roleTypes: ['VLSI', 'Hardware', 'Memory'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 30, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Memory chip maker — DRAM/SSD expertise.',
        whyJoin: ['Memory Innovation', 'Manufacturing Scale', 'Global Presence'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'nxp',
        name: 'NXP Semiconductors',
        tier: 'Tier 2',
        majors: ['ECE'],
        domains: ['Automotive', 'Embedded', 'NFC'],
        roleTypes: ['Embedded', 'Firmware', 'VLSI'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 28, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Automotive chips and NFC/security.',
        whyJoin: ['Automotive Tech', 'Secure IoT', 'European Culture'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'bosch-ece',
        name: 'Bosch',
        tier: 'Tier 2',
        majors: ['ECE', 'EEE'],
        domains: ['Automotive', 'Embedded', 'MEMS'],
        roleTypes: ['Embedded', 'Firmware', 'Hardware'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 10, maxLPA: 25, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Automotive electronics and sensors.',
        whyJoin: ['Automotive Leader', 'German Engineering', 'Stability'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
];

const ECE_TIER3: Company[] = [
    {
        id: 'tata-elxsi',
        name: 'Tata Elxsi',
        tier: 'Tier 3',
        majors: ['ECE'],
        domains: ['Embedded', 'Automotive', 'Design'],
        roleTypes: ['Embedded', 'Firmware', 'Design'],
        location: 'On-site',
        companyType: 'Service',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 6, maxLPA: 15, inHandPercent: 72 },
        culture: { wlb: 'Yellow', learning: 'Medium' },
        description: 'Design & tech services for automotive.',
        whyJoin: ['Design Services', 'Automotive Focus', 'Tata Group'],
        levels: ['Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'ltts',
        name: 'L&T Technology Services',
        tier: 'Tier 3',
        majors: ['ECE', 'Core'],
        domains: ['Embedded', 'Engineering', 'Automotive'],
        roleTypes: ['Embedded', 'Design', 'Testing'],
        location: 'On-site',
        companyType: 'Service',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 6, maxLPA: 15, inHandPercent: 70 },
        culture: { wlb: 'Yellow', learning: 'Medium' },
        description: 'Engineering services across domains.',
        whyJoin: ['Multi-domain Exposure', 'Global Projects', 'L&T Brand'],
        levels: ['Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'bel',
        name: 'BEL',
        tier: 'Tier 3',
        majors: ['ECE', 'EEE'],
        domains: ['Defense', 'Electronics', 'Communication'],
        roleTypes: ['Hardware', 'Embedded', 'RF'],
        location: 'On-site',
        companyType: 'PSU',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 18, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Defense PSU for electronics.',
        whyJoin: ['National Service', 'Job Security', 'Defense Tech'],
        levels: ['Probationary Officer', 'Senior Engineer']
    },
];

// ============================================
// EEE COMPANIES
// ============================================

const EEE_TIER1: Company[] = [
    {
        id: 'siemens-energy',
        name: 'Siemens',
        tier: 'Tier 1',
        majors: ['EEE'],
        domains: ['Power', 'Automation', 'Energy'],
        roleTypes: ['Power Engineer', 'Control', 'Automation'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 72 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Global power and automation leader.',
        whyJoin: ['Energy Innovation', 'Global MNC', 'Great Training'],
        levels: ['GET', 'Engineer', 'Senior Engineer']
    },
    {
        id: 'abb',
        name: 'ABB',
        tier: 'Tier 1',
        majors: ['EEE'],
        domains: ['Power', 'Automation', 'Robotics'],
        roleTypes: ['Power Engineer', 'Automation', 'Control'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 72 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Swiss power & automation multinational.',
        whyJoin: ['Robotics Leader', 'Sustainable Tech', 'European Culture'],
        levels: ['GET', 'Engineer', 'Senior Engineer']
    },
    {
        id: 'schneider',
        name: 'Schneider Electric',
        tier: 'Tier 1',
        majors: ['EEE'],
        domains: ['Power', 'Energy Management', 'Automation'],
        roleTypes: ['Power Engineer', 'Automation', 'Energy'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 72 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'French energy management multinational.',
        whyJoin: ['Sustainability', 'Smart Grid focus', 'Great Culture'],
        levels: ['GET', 'Engineer', 'Senior Engineer']
    },
];

const EEE_TIER2: Company[] = [
    {
        id: 'tata-power',
        name: 'Tata Power',
        tier: 'Tier 2',
        majors: ['EEE'],
        domains: ['Power', 'Energy', 'Renewables'],
        roleTypes: ['Power Engineer', 'Operations', 'Maintenance'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 7, maxLPA: 18, inHandPercent: 70 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Power utility with renewable focus.',
        whyJoin: ['Renewable Energy', 'Tata Ethics', 'Green Transition'],
        levels: ['GET', 'Assistant Manager', 'Senior Manager']
    },
    {
        id: 'lt-electrical',
        name: 'L&T Electrical',
        tier: 'Tier 2',
        majors: ['EEE'],
        domains: ['Power', 'Switchgear', 'Infrastructure'],
        roleTypes: ['Power Engineer', 'Design', 'Projects'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 70 },
        culture: { wlb: 'Yellow', learning: 'Medium' },
        description: 'Indian conglomerate with electrical division.',
        whyJoin: ['Core Engineering', 'Construction Giant', 'Nation Building'],
        levels: ['GET', 'Senior Engineer', 'Assistant Manager']
    },
];

const EEE_TIER3: Company[] = [
    {
        id: 'ntpc',
        name: 'NTPC',
        tier: 'Tier 3',
        majors: ['EEE'],
        domains: ['Power Generation', 'Energy'],
        roleTypes: ['Power Engineer', 'Operations', 'Maintenance'],
        location: 'On-site',
        companyType: 'PSU',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 10, maxLPA: 22, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Largest power producer PSU.',
        whyJoin: ['Maharatna Status', 'Best in Class Pay', 'Campus Townships'],
        levels: ['E2', 'E3', 'E4']
    },
    {
        id: 'powergrid',
        name: 'Power Grid Corporation',
        tier: 'Tier 3',
        majors: ['EEE'],
        domains: ['Transmission', 'Grid', 'Power'],
        roleTypes: ['Power Engineer', 'Transmission', 'Operations'],
        location: 'On-site',
        companyType: 'PSU',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 10, maxLPA: 22, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Transmission grid operator PSU.',
        whyJoin: ['Grid Management', 'Stable Career', 'Government Perks'],
        levels: ['Engineer']
    },
    {
        id: 'bhel',
        name: 'BHEL',
        tier: 'Tier 3',
        majors: ['EEE', 'Core'],
        domains: ['Power Equipment', 'Manufacturing'],
        roleTypes: ['Power Engineer', 'Manufacturing', 'Design'],
        location: 'On-site',
        companyType: 'PSU',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 18, inHandPercent: 72 },
        culture: { wlb: 'Green', learning: 'Low' },
        description: 'Maharatna PSU for power equipment.',
        whyJoin: ['Heavy Industries', 'Manufacturing Scale', 'Work Life Balance'],
        levels: ['Engineer']
    },
];

// ============================================
// CORE/MECHANICAL COMPANIES
// ============================================

const CORE_TIER1: Company[] = [
    {
        id: 'boeing',
        name: 'Boeing',
        tier: 'Tier 1',
        majors: ['Core'],
        domains: ['Aerospace', 'Manufacturing', 'Defense'],
        roleTypes: ['Mechanical', 'Design', 'Aerospace'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 15, maxLPA: 35, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Aerospace giant with India R&D.',
        whyJoin: ['Aviation Leader', 'Complex Problems', 'Global Mobility'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
    {
        id: 'airbus',
        name: 'Airbus',
        tier: 'Tier 1',
        majors: ['Core'],
        domains: ['Aerospace', 'Manufacturing', 'Design'],
        roleTypes: ['Mechanical', 'Design', 'Aerospace'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 15, maxLPA: 35, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'European aerospace with Bangalore engineering.',
        whyJoin: ['Fly-by-wire Tech', 'European Work Culture', 'Innovation'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior', 'Expert']
    },
    {
        id: 'isro',
        name: 'ISRO',
        tier: 'Tier 1',
        majors: ['Core', 'ECE'],
        domains: ['Space', 'Aerospace', 'Research'],
        roleTypes: ['Scientist', 'Mechanical', 'Aerospace'],
        location: 'On-site',
        companyType: 'PSU',
        difficulty: 'Hard',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 80 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'Indian space agency — Chandrayaan, Mangalyaan.',
        whyJoin: ['Space Exploration', 'National Pride', 'Scientific Research'],
        levels: ['Scientist/Engineer-SC', 'SD', 'SE', 'SF', 'SG']
    },
];

const CORE_TIER2: Company[] = [
    {
        id: 'tata-motors',
        name: 'Tata Motors',
        tier: 'Tier 2',
        majors: ['Core'],
        domains: ['Automotive', 'Manufacturing', 'EV'],
        roleTypes: ['Mechanical', 'Design', 'Manufacturing'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 70 },
        culture: { wlb: 'Yellow', learning: 'Medium' },
        description: 'JLR parent with EV push.',
        whyJoin: ['Bar Raiser Culture', 'Fast Promotion Velocity', 'Working on AWS Bedrock / Q'],
        levels: ['GET']
    },
    {
        id: 'mahindra',
        name: 'Mahindra & Mahindra',
        tier: 'Tier 2',
        majors: ['Core'],
        domains: ['Automotive', 'Tractors', 'Manufacturing'],
        roleTypes: ['Mechanical', 'Design', 'Manufacturing'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 70 },
        culture: { wlb: 'Yellow', learning: 'Medium' },
        description: 'SUV and tractor manufacturer.',
        whyJoin: ['Core Automotive', 'Off-road tech', 'Rise Philosophy'],
        levels: ['GET', 'Senior Manager']
    },
    {
        id: 'bosch-auto',
        name: 'Bosch (Automotive)',
        tier: 'Tier 2',
        majors: ['Core'],
        domains: ['Automotive', 'Manufacturing', 'Components'],
        roleTypes: ['Mechanical', 'Design', 'Testing'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 10, maxLPA: 25, inHandPercent: 74 },
        culture: { wlb: 'Green', learning: 'High' },
        description: 'German automotive components leader.',
        whyJoin: ['Bosch Way', 'Precision Engineering', 'Automotive Future'],
        levels: ['Internship', 'Entry Level', 'Mid Level', 'Senior']
    },
];

const CORE_TIER3: Company[] = [
    {
        id: 'lnt',
        name: 'Larsen & Toubro',
        tier: 'Tier 3',
        majors: ['Core'],
        domains: ['Infrastructure', 'Manufacturing', 'Construction'],
        roleTypes: ['Site Engineer', 'Design', 'Projects'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Medium',
        internFriendly: true,
        salary: { minLPA: 6, maxLPA: 15, inHandPercent: 68 },
        culture: { wlb: 'Yellow', learning: 'Medium' },
        description: 'EPC giant with infrastructure projects.',
        whyJoin: ['Mega Projects', 'Construction Leader', 'Field Exposure'],
        levels: ['GET', 'Construction Manager']
    },
    {
        id: 'tata-steel',
        name: 'Tata Steel',
        tier: 'Tier 3',
        majors: ['Core'],
        domains: ['Steel', 'Manufacturing', 'Metallurgy'],
        roleTypes: ['Mechanical', 'Metallurgy', 'Operations'],
        location: 'On-site',
        companyType: 'Product',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 72 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Steel pioneer with Jamshedpur base.',
        whyJoin: ['Steel Manufacturing', 'Legacy', 'Employee Care'],
        levels: ['GET', 'Senior Manager']
    },
    {
        id: 'ongc',
        name: 'ONGC',
        tier: 'Tier 3',
        majors: ['Core'],
        domains: ['Oil & Gas', 'Energy', 'Exploration'],
        roleTypes: ['Mechanical', 'Petroleum', 'Operations'],
        location: 'On-site',
        companyType: 'PSU',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 12, maxLPA: 25, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Oil & gas Maharatna PSU.',
        whyJoin: ['Energy Sector', 'Highest PSU Pay', 'Field Life'],
        levels: ['GT', 'E1', 'E2', 'E3', 'E4']
    },
    {
        id: 'hal',
        name: 'HAL',
        tier: 'Tier 3',
        majors: ['Core', 'ECE'],
        domains: ['Aerospace', 'Defense', 'Manufacturing'],
        roleTypes: ['Mechanical', 'Aerospace', 'Manufacturing'],
        location: 'On-site',
        companyType: 'PSU',
        difficulty: 'Easy',
        internFriendly: true,
        salary: { minLPA: 8, maxLPA: 20, inHandPercent: 75 },
        culture: { wlb: 'Green', learning: 'Medium' },
        description: 'Defense PSU for aircraft manufacturing.',
        whyJoin: ['Fighter Jets', 'Aviation Tech', 'Defense Service'],
        levels: ['Design Trainee', 'Engineer']
    },
];

// ============================================
// EXPORT ALL COMPANIES
// ============================================

export const COMPANIES: Company[] = [
    ...CS_TIER1, ...CS_TIER2, ...CS_TIER3,
    ...ECE_TIER1, ...ECE_TIER2, ...ECE_TIER3,
    ...EEE_TIER1, ...EEE_TIER2, ...EEE_TIER3,
    ...CORE_TIER1, ...CORE_TIER2, ...CORE_TIER3,
];

// Get unique values for filters
export const ALL_DOMAINS = Array.from(new Set(COMPANIES.flatMap(c => c.domains))).sort();

// Simplified Domain Categories for Better Filtering
export const SIMPLIFIED_DOMAINS = [
    'Software Engineering',
    'AI/ML & Data',
    'Cloud & Infrastructure',
    'Finance & Trading',
    'Security',
    'Hardware & Semiconductors',
    'Mobile',
    'Product & Design',
    'Research',
    'Other'
] as const;

export const ALL_ROLE_TYPES = Array.from(new Set(COMPANIES.flatMap(c => c.roleTypes))).sort();
